name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pguyot/arm-runner-action@v2.3.1 
      id: build_image
      with:
        base_image: raspios_lite:latest
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: OpenHD_fmt/OpenHD_fmt
        import_github_env: true
        commands: |
            cd OpenHD_fmt
            ls -a
            sudo chmod +x install_dep.sh
            sudo ./install_dep.sh
            mkdir build 
            cd build
            cmake ..
            mkdir fmt-package
            sudo make DESTDIR=fmt-package -j4 install
            fpm -a armhf -s dir -t deb -n fmt -v 8.1 -C fmt-package -p fmt_VERSION_ARCH.deb
            ls -a

    - name: update
      run: ls -a

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "FMT"
        path: |
          *.deb
          *.log


    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-1-alpha"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "*.deb"


      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
